os: linux
group: stable
dist: trusty
sudo: required
language: generic

env:
  DOCKER_COMPOSE_VERSION: 1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

before_script:
  - docker-compose up -d vtiger
  - sleep 5
  - docker-compose exec mysql bash -c "mysql --skip-column-names --batch --raw -uroot -p\$MYSQL_ROOT_PASSWORD \$MYSQL_DATABASE -e \"SELECT accesskey FROM vtiger_users WHERE user_name='admin'\""
  - docker-compose ps
  - docker-compose run --rm composer install --no-interaction --prefer-source

script:
  - docker-compose run --rm phpunit tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
